services:
  fastapi:
    env_file:
      - ./.env
    build:
      context: ./backend  
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - rag_db:/app
    networks:
      - python-network

  streamlit:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    depends_on:
      - fastapi
    ports:
      - "8501:8501"
    networks:
      - python-network

networks:
  python-network:
    driver: bridge

volumes:
  rag_db:
